package index

import (
	"bytes"
	"strings"
	"unicode/utf8"

	"github.com/don-works/mcplexer/internal/store"
)

const (
	chunkSchemaVersion = 1
	chunkMaxBytes      = 8 * 1024
	chunkOverlapBytes  = 768
	maxChunksPerFile   = 128
	maxChunkCodeTokens = 512
	maxChunkSymbols    = 12
	maxWorkspaceChunks = 250_000
)

// chunkSource splits an allowed UTF-8 source file into bounded, overlapping
// citation units. Boundaries prefer newlines, while byte fallback guarantees
// progress on long (but not minified) lines. Every returned chunk is safe for
// both FTS and the optional local embedding queue.
func chunkSource(rel string, src []byte, symbols []store.CodeIndexSymbol) ([]store.CodeIndexChunk, bool) {
	if !ShouldIndexPath(rel) || len(src) == 0 || !utf8.Valid(src) || likelyGeneratedSource(src) {
		return nil, false
	}
	var chunks []store.CodeIndexChunk
	truncated := false
	for start := 0; start < len(src); {
		if len(chunks) >= maxChunksPerFile {
			truncated = true
			break
		}
		end := start + chunkMaxBytes
		if end >= len(src) {
			end = len(src)
		} else {
			// Prefer a line boundary in the latter half of the window.
			if i := bytes.LastIndexByte(src[start+chunkMaxBytes/2:end], '\n'); i >= 0 {
				end = start + chunkMaxBytes/2 + i + 1
			}
			for end > start && !utf8.RuneStart(src[end]) {
				end--
			}
		}
		if end <= start {
			break
		}
		startLine := 1 + bytes.Count(src[:start], []byte{'\n'})
		endLine := startLine + bytes.Count(src[start:end], []byte{'\n'})
		if end > start && src[end-1] == '\n' && endLine > startLine {
			endLine--
		}
		content := string(src[start:end])
		names, kind := symbolsForLines(symbols, startLine, endLine)
		chunks = append(chunks, store.CodeIndexChunk{
			Ordinal:      len(chunks),
			Kind:         kind,
			SymbolName:   strings.Join(names, " "),
			SymbolTokens: tokenString(strings.Join(names, " ")),
			Path:         rel,
			PathTokens:   tokenString(rel),
			CodeTokens:   boundedCodeTokens(content),
			StartLine:    startLine,
			EndLine:      maxInt(startLine, endLine),
			Content:      content,
			ContentHash:  hashBytes([]byte(content)),
		})
		if end == len(src) {
			break
		}
		next := end - chunkOverlapBytes
		if next <= start {
			next = end
		}
		// Start overlap at a line boundary when one is nearby, preserving
		// stable citations as edits occur before the chunk.
		if i := bytes.IndexByte(src[next:end], '\n'); i >= 0 && next+i+1 < end {
			next += i + 1
		}
		for next < len(src) && !utf8.RuneStart(src[next]) {
			next++
		}
		start = next
	}
	return chunks, truncated
}

func symbolsForLines(symbols []store.CodeIndexSymbol, start, end int) ([]string, string) {
	seen := map[string]bool{}
	var names []string
	kind := "source"
	for _, sym := range symbols {
		symEnd := sym.EndLine
		if symEnd <= 0 {
			symEnd = sym.StartLine
		}
		if sym.StartLine > end || symEnd < start || seen[sym.Name] {
			continue
		}
		seen[sym.Name] = true
		names = append(names, sym.Name)
		if len(names) == 1 {
			kind = sym.Kind
		} else if kind != sym.Kind {
			kind = "source"
		}
		if len(names) >= maxChunkSymbols {
			break
		}
	}
	return names, kind
}

func boundedCodeTokens(content string) string {
	all := splitIdent(content)
	seen := make(map[string]bool, len(all))
	out := make([]string, 0, minInt(len(all), maxChunkCodeTokens))
	for _, token := range all {
		if len(token) < 2 || seen[token] {
			continue
		}
		seen[token] = true
		out = append(out, token)
		if len(out) >= maxChunkCodeTokens {
			break
		}
	}
	return strings.Join(out, " ")
}

// likelyGeneratedSource catches generated/minified content whose path did not
// advertise it. It runs after the 1 MiB and binary gates but before extraction,
// chunking, or embedding.
func likelyGeneratedSource(src []byte) bool {
	// Generated markers only count in a leading COMMENT. Searching arbitrary
	// bytes caused source that implements this detector (and code containing a
	// "do not edit" UI string) to exclude itself.
	prefixLines := bytes.Split(src[:minInt(len(src), 4096)], []byte{'\n'})
	if len(prefixLines) > 24 {
		prefixLines = prefixLines[:24]
	}
	for _, raw := range prefixLines {
		line := strings.ToLower(strings.TrimSpace(string(raw)))
		if !isGeneratedCommentLine(line) {
			continue
		}
		for _, marker := range []string{
			"code generated", "do not edit", "@generated", "automatically generated",
			"this file was generated", "generated by protoc",
		} {
			if strings.Contains(line, marker) {
				return true
			}
		}
	}
	if len(src) > 64*1024 && bytes.Count(src, []byte{'\n'}) < 4 {
		return true
	}
	for _, line := range bytes.Split(src, []byte{'\n'}) {
		if len(line) > 32*1024 {
			return true
		}
	}
	return false
}

func isGeneratedCommentLine(line string) bool {
	for _, prefix := range []string{"//", "#", "/*", "*", "<!--", ";", "--"} {
		if strings.HasPrefix(line, prefix) {
			return true
		}
	}
	return false
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}
