package index

import (
	"strings"
	"testing"

	"github.com/don-works/mcplexer/internal/store"
)

func TestChunkSourceCitationsOverlapAndSymbols(t *testing.T) {
	var src strings.Builder
	for i := 0; i < 500; i++ {
		src.WriteString("line with validateCredentials and session token logic\n")
	}
	chunks, truncated := chunkSource("internal/auth/service.go", []byte(src.String()), []store.CodeIndexSymbol{{
		Name: "ValidateCredentials", Kind: "func", StartLine: 20, EndLine: 180,
	}})
	if truncated || len(chunks) < 2 {
		t.Fatalf("chunks=%d truncated=%v, want multiple complete chunks", len(chunks), truncated)
	}
	if chunks[0].StartLine != 1 || chunks[0].EndLine < chunks[1].StartLine {
		t.Fatalf("citations are not overlapping/stable: first=%d-%d second=%d-%d",
			chunks[0].StartLine, chunks[0].EndLine, chunks[1].StartLine, chunks[1].EndLine)
	}
	if !strings.Contains(chunks[0].SymbolTokens, "validate credentials") ||
		!strings.Contains(chunks[0].CodeTokens, "session") {
		t.Fatalf("chunk metadata missing identifiers: %+v", chunks[0])
	}
	for i, c := range chunks {
		if c.Ordinal != i || c.Path != "internal/auth/service.go" || len(c.Content) > chunkMaxBytes {
			t.Fatalf("bad chunk %d: %+v", i, c)
		}
	}
}

func TestChunkSourceRejectsDeniedGeneratedAndInvalidUTF8(t *testing.T) {
	cases := []struct {
		path string
		src  []byte
	}{
		{"node_modules/pkg/index.js", []byte("export function x() {}")},
		{"src/generated.go", []byte("// Code generated by tool. DO NOT EDIT.\npackage x")},
		{"src/bad.go", []byte{0xff, 0xfe}},
		{"src/bundle.js", []byte(strings.Repeat("x", 70*1024))},
	}
	for _, tc := range cases {
		if chunks, _ := chunkSource(tc.path, tc.src, nil); len(chunks) != 0 {
			t.Errorf("chunkSource(%q) returned %d chunks", tc.path, len(chunks))
		}
	}
}

func TestLikelyGeneratedSourceRequiresCommentHeader(t *testing.T) {
	legitimate := []byte(`package detector

var generatedMarkers = []string{"code generated", "do not edit", "@generated"}
func RenderNotice() string { return "this file was generated successfully" }
`)
	if likelyGeneratedSource(legitimate) {
		t.Fatal("marker string literals must not classify maintained source as generated")
	}
	for _, generated := range [][]byte{
		[]byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"),
		[]byte("# This file was generated automatically\nvalue = 1\n"),
		[]byte("/* @generated */\nexport const x = 1\n"),
	} {
		if !likelyGeneratedSource(generated) {
			t.Fatalf("generated comment header not detected: %q", generated)
		}
	}
}

func TestChunkSourceCapsPathologicalFile(t *testing.T) {
	src := strings.Repeat("abcdefghij\n", 200_000)
	chunks, truncated := chunkSource("src/huge.txt", []byte(src), nil)
	if len(chunks) != maxChunksPerFile || !truncated {
		t.Fatalf("chunks=%d truncated=%v, want cap=%d", len(chunks), truncated, maxChunksPerFile)
	}
}

func TestWorkspaceChunkCapMarksOnlyTruncation(t *testing.T) {
	chunks := make([]store.CodeIndexChunk, 3)
	if got, truncated := fitWorkspaceChunkBudget(chunks, 3); truncated || len(got) != 3 {
		t.Fatalf("exact budget = len %d truncated %v", len(got), truncated)
	}
	if got, truncated := fitWorkspaceChunkBudget(chunks, 1); !truncated || len(got) != 1 {
		t.Fatalf("limited budget = len %d truncated %v", len(got), truncated)
	}
	if got, truncated := fitWorkspaceChunkBudget(chunks, -1); !truncated || len(got) != 0 {
		t.Fatalf("negative budget = len %d truncated %v", len(got), truncated)
	}
}
