package index

import (
	"strings"
	"testing"

	"github.com/don-works/mcplexer/internal/store"
)

func TestChunkSourceCitationsOverlapAndSymbols(t *testing.T) {
	var src strings.Builder
	for i := 0; i < 500; i++ {
		src.WriteString("line with validateCredentials and session token logic\n")
	}
	chunks, truncated := chunkSource("internal/auth/service.go", []byte(src.String()), []store.CodeIndexSymbol{{
		Name: "ValidateCredentials", Kind: "func", StartLine: 20, EndLine: 180,
	}})
	if truncated || len(chunks) < 2 {
		t.Fatalf("chunks=%d truncated=%v, want multiple complete chunks", len(chunks), truncated)
	}
	if chunks[0].StartLine != 1 || chunks[0].EndLine < chunks[1].StartLine {
		t.Fatalf("citations are not overlapping/stable: first=%d-%d second=%d-%d",
			chunks[0].StartLine, chunks[0].EndLine, chunks[1].StartLine, chunks[1].EndLine)
	}
	if !strings.Contains(chunks[0].SymbolTokens, "validate credentials") ||
		!strings.Contains(chunks[0].CodeTokens, "session") {
		t.Fatalf("chunk metadata missing identifiers: %+v", chunks[0])
	}
	for i, c := range chunks {
		if c.Ordinal != i || c.Path != "internal/auth/service.go" || len(c.Content) > chunkMaxBytes {
			t.Fatalf("bad chunk %d: %+v", i, c)
		}
	}
}

func TestChunkSourceRejectsDeniedGeneratedAndInvalidUTF8(t *testing.T) {
	cases := []struct {
		path string
		src  []byte
	}{
		{"node_modules/pkg/index.js", []byte("export function x() {}")},
		{"src/generated.go", []byte("// Code generated by tool. DO NOT EDIT.\npackage x")},
		{"src/bad.go", []byte{0xff, 0xfe}},
		{"src/bundle.js", []byte(strings.Repeat("x", 70*1024))},
	}
	for _, tc := range cases {
		if chunks, _ := chunkSource(tc.path, tc.src, nil); len(chunks) != 0 {
			t.Errorf("chunkSource(%q) returned %d chunks", tc.path, len(chunks))
		}
	}
}

func TestChunkSourceCapsPathologicalFile(t *testing.T) {
	src := strings.Repeat("abcdefghij\n", 200_000)
	chunks, truncated := chunkSource("src/huge.txt", []byte(src), nil)
	if len(chunks) != maxChunksPerFile || !truncated {
		t.Fatalf("chunks=%d truncated=%v, want cap=%d", len(chunks), truncated, maxChunksPerFile)
	}
}
