// digest.go — write-through to ~/.mcplexer/memory-exports/<scope>.md
// so existing harnesses (Claude Code, Cursor, Codex) can @import a
// curated digest of mcplexer's memories into their own context. We
// never edit the user's CLAUDE.md — the dashboard prints a copyable
// "@import …" line and the user pastes it once.
package memory

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/don-works/mcplexer/internal/store"
)

// Digester renders + persists a memory digest for one scope (workspace
// or global). Implementations are stateless except for the target
// directory; concurrent calls are safe via single-writer-per-scope
// serialization at the Service layer.
type Digester interface {
	Write(ctx context.Context, scope string, entries []store.MemoryEntry) error
	Path(scope string) string
}

// FileDigester writes scope-named markdown files under exportDir.
// scope "" or "global" → memory-exports/global.md
// scope = workspace_id → memory-exports/workspace-<id>.md
type FileDigester struct {
	Dir string
	// MaxEntries caps the digest size to keep it import-friendly.
	// Defaults to digestMaxEntries when zero.
	MaxEntries int
}

// NewFileDigester constructs a digester rooted at dir. The directory
// is created on first Write if absent.
func NewFileDigester(dir string) *FileDigester {
	return &FileDigester{Dir: dir, MaxEntries: digestMaxEntries}
}

// Path returns the absolute path the digest for scope will be written
// to. Useful for the dashboard to render a copyable @import line.
func (d *FileDigester) Path(scope string) string {
	return filepath.Join(d.Dir, scopeFilename(scope))
}

// Write renders entries as markdown and writes (atomically via rename)
// to Path(scope). Empty entries clear the file by writing an empty
// document so stale content never leaks back into the harness.
func (d *FileDigester) Write(
	_ context.Context, scope string, entries []store.MemoryEntry,
) error {
	if d == nil || d.Dir == "" {
		return nil
	}
	if err := os.MkdirAll(d.Dir, 0o755); err != nil {
		return fmt.Errorf("digest mkdir: %w", err)
	}
	limit := d.MaxEntries
	if limit <= 0 {
		limit = digestMaxEntries
	}
	if len(entries) > limit {
		entries = entries[:limit]
	}
	target := d.Path(scope)
	body := renderDigest(scope, target, entries)
	tmp := target + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return fmt.Errorf("digest write tmp: %w", err)
	}
	if err := os.Rename(tmp, target); err != nil {
		return fmt.Errorf("digest rename: %w", err)
	}
	return nil
}

// scopeFilename maps a scope id to a safe filename. "global" or empty
// → global.md; anything else → workspace-<sanitised>.md.
func scopeFilename(scope string) string {
	s := strings.TrimSpace(scope)
	if s == "" || s == "global" {
		return "global.md"
	}
	return "workspace-" + safeSegment(s) + ".md"
}

func safeSegment(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z',
			r >= 'A' && r <= 'Z',
			r >= '0' && r <= '9',
			r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// renderDigest produces the markdown body. Facts come first (compact
// bullet list, one per line), notes second (header + indented preview).
// Pinned items get a "* " marker. Each entry includes a short link tag
// so the user can grep back to the canonical record in the dashboard.
// path is the absolute file path the digest will be written to, printed
// in the copyable @import hint.
func renderDigest(scope, path string, entries []store.MemoryEntry) string {
	var b strings.Builder
	label := scope
	if label == "" {
		label = "global"
	}
	fmt.Fprintf(&b, "# mcplexer memory · %s\n\n", label)
	fmt.Fprintf(&b, "_Auto-generated by mcplexer. Add `@%s` to your CLAUDE.md to share with Claude Code._\n",
		path)
	fmt.Fprintf(&b, "_Last updated: %s · %d entries._\n\n",
		time.Now().UTC().Format("2006-01-02 15:04 UTC"), len(entries))
	fmt.Fprintf(&b, "> **Memory is managed by mcplexer.** Use `memory.recall({query})` and `memory.save({...})` inside `mcpx__execute_code`. Do not write to harness-native memory files.\n\n")
	if len(entries) == 0 {
		b.WriteString("_(no memories saved yet)_\n")
		return b.String()
	}
	facts, notes := partitionByKind(entries)
	if len(facts) > 0 {
		b.WriteString("## Facts\n\n")
		for _, e := range facts {
			marker := "- "
			if e.Pinned {
				marker = "- ★ "
			}
			fmt.Fprintf(&b, "%s**%s** — %s\n", marker, e.Name, oneLine(e.Content))
		}
		b.WriteByte('\n')
	}
	if len(notes) > 0 {
		b.WriteString("## Notes\n\n")
		for _, e := range notes {
			marker := ""
			if e.Pinned {
				marker = "★ "
			}
			fmt.Fprintf(&b, "### %s%s\n\n%s\n\n",
				marker, e.Name, truncate(e.Content, 1024))
		}
	}
	return b.String()
}

func partitionByKind(in []store.MemoryEntry) (facts, notes []store.MemoryEntry) {
	for _, e := range in {
		switch e.Kind {
		case store.MemoryKindFact:
			facts = append(facts, e)
		default:
			notes = append(notes, e)
		}
	}
	// Pinned first within each group; then alphabetical by name for a
	// stable, human-readable digest.
	sort.SliceStable(facts, func(i, j int) bool {
		if facts[i].Pinned != facts[j].Pinned {
			return facts[i].Pinned
		}
		return facts[i].Name < facts[j].Name
	})
	sort.SliceStable(notes, func(i, j int) bool {
		if notes[i].Pinned != notes[j].Pinned {
			return notes[i].Pinned
		}
		return notes[i].Name < notes[j].Name
	})
	return facts, notes
}

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	return strings.TrimSpace(s)
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max] + "…"
}
