package brain

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// vaultIndexFile is the generated human-facing map at the vault root.
// It maps raw workspace directories to display names and live record
// counts without a risky directory-rename migration.
const vaultIndexFile = "INDEX.md"

// isVaultIndexPath reports whether path is the generated vault-root
// INDEX.md, a derived projection that is never an indexable record.
func (ix *Indexer) isVaultIndexPath(path string) bool {
	return filepath.Clean(path) == filepath.Join(ix.cfg.Dir, vaultIndexFile)
}

// WriteVaultIndex generates or refreshes <Dir>/INDEX.md. Identical
// content is not rewritten. The write is marked in the self-write set so
// a watcher echo is suppressed if the root is ever watched.
func (ix *Indexer) WriteVaultIndex(ctx context.Context) error {
	root := filepath.Join(ix.cfg.Dir, "workspaces")
	entries, err := os.ReadDir(root)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("brain: vault index read workspaces: %w", err)
	}
	var b strings.Builder
	b.WriteString("# Brain vault index\n\n")
	b.WriteString("Generated by mcplexer on every full reindex; do not edit by hand.\n")
	b.WriteString("Maps each workspace directory to its display name and record counts.\n\n")
	b.WriteString("| Workspace | Directory | Tasks | Memories | People |\n")
	b.WriteString("| --- | --- | ---: | ---: | ---: |\n")
	for _, e := range entries {
		if !e.IsDir() || (len(e.Name()) > 1 && e.Name()[0] == '.') {
			continue
		}
		b.WriteString(ix.vaultIndexRow(ctx, e.Name()))
	}
	data := []byte(b.String())
	path := filepath.Join(ix.cfg.Dir, vaultIndexFile)
	if cur, rErr := os.ReadFile(path); rErr == nil && hashBytes(cur) == hashBytes(data) {
		return nil
	}
	ix.selfWrites.Mark(path, hashBytes(data))
	if err := atomicWrite(path, data); err != nil {
		return fmt.Errorf("brain: write %s: %w", path, err)
	}
	return nil
}

// vaultIndexRow renders one workspace's table row: display name, a
// relative markdown link to the dir, and on-disk record counts.
func (ix *Indexer) vaultIndexRow(ctx context.Context, dir string) string {
	display := dir
	if ws, err := ix.store.GetWorkspace(ctx, dir); err == nil && ws != nil &&
		strings.TrimSpace(ws.Name) != "" {
		display = ws.Name
	}
	wsDir := filepath.Join(ix.cfg.Dir, "workspaces", dir)
	tasks := countMarkdownFiles(filepath.Join(wsDir, taskSubdir))
	memories := countMarkdownFiles(filepath.Join(wsDir, memorySubdir)) +
		countMarkdownFiles(filepath.Join(wsDir, memorySubdir, memoryFactsSubdir))
	people := countMarkdownFiles(filepath.Join(wsDir, crmSubdir, peopleSubdir))
	return fmt.Sprintf("| %s | [%s](workspaces/%s/) | %d | %d | %d |\n",
		display, dir, dir, tasks, memories, people)
}

// countMarkdownFiles counts the .md files directly under dir. A missing
// dir counts zero.
func countMarkdownFiles(dir string) int {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0
	}
	n := 0
	for _, e := range entries {
		if !e.IsDir() && isMarkdown(e.Name()) {
			n++
		}
	}
	return n
}
