package config

import (
	"encoding/json"

	"github.com/don-works/mcplexer/internal/store"
)

// defaultDownstreamServers defines the built-in MCP servers seeded on first run.
// Servers marked Disabled require user configuration (API keys, paths) before use.
var defaultDownstreamServers = []store.DownstreamServer{
	// ── HTTP (Streamable HTTP) servers — OAuth auto-discovery, one-click connect ──
	{
		ID:             "github",
		Name:           "GitHub",
		Transport:      "http",
		URL:            strPtr("https://api.githubcopilot.com/mcp/"),
		ToolNamespace:  "github",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "linear",
		Name:           "Linear",
		Transport:      "http",
		URL:            strPtr("https://mcp.linear.app/mcp"),
		ToolNamespace:  "linear",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "clickup",
		Name:           "ClickUp",
		Transport:      "http",
		URL:            strPtr("https://mcp.clickup.com/mcp"),
		ToolNamespace:  "clickup",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "vercel",
		Name:           "Vercel",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "mcp-remote", "https://mcp.vercel.com"]`),
		ToolNamespace:  "vercel",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "notion",
		Name:           "Notion",
		Transport:      "http",
		URL:            strPtr("https://mcp.notion.com/mcp"),
		ToolNamespace:  "notion",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             obsidianServerID,
		Name:           "Obsidian",
		Transport:      "http",
		URL:            strPtr("http://127.0.0.1:27123/mcp/"),
		ToolNamespace:  "obsidian",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "stripe",
		Name:           "Stripe",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "mcp-remote", "https://mcp.stripe.com"]`),
		ToolNamespace:  "stripe",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "sentry",
		Name:           "Sentry",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "mcp-remote", "https://mcp.sentry.dev/mcp"]`),
		ToolNamespace:  "sentry",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "atlassian",
		Name:           "Atlassian (Jira + Confluence)",
		Transport:      "http",
		URL:            strPtr("https://mcp.atlassian.com/v1/mcp"),
		ToolNamespace:  "atlassian",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "cloudflare",
		Name:           "Cloudflare",
		Transport:      "http",
		URL:            strPtr("https://mcp.cloudflare.com/mcp"),
		ToolNamespace:  "cloudflare",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "supabase",
		Name:           "Supabase",
		Transport:      "http",
		URL:            strPtr("https://mcp.supabase.com/mcp"),
		ToolNamespace:  "supabase",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "neon",
		Name:           "Neon",
		Transport:      "http",
		URL:            strPtr("https://mcp.neon.tech/mcp"),
		ToolNamespace:  "neon",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "datadog",
		Name:           "Datadog",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "mcp-remote", "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp"]`),
		ToolNamespace:  "datadog",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "asana",
		Name:           "Asana",
		Transport:      "http",
		URL:            strPtr("https://mcp.asana.com/v2/mcp"),
		ToolNamespace:  "asana",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "hubspot",
		Name:           "HubSpot",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "mcp-remote", "https://mcp.hubspot.com"]`),
		ToolNamespace:  "hubspot",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},
	{
		ID:             "azdo",
		Name:           "Azure DevOps",
		Transport:      "http",
		URL:            strPtr("https://mcp.developer.microsoft.com/api/mcp"),
		ToolNamespace:  "azdo",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "excalidraw",
		Name:           "Excalidraw",
		Transport:      "http",
		URL:            strPtr("https://mcp.excalidraw.com/mcp"),
		ToolNamespace:  "excalidraw",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Source:         "default",
	},

	// ── Remote OAuth servers that require registered client credentials ──
	{
		ID:             "slack",
		Name:           "Slack",
		Transport:      "http",
		URL:            strPtr("https://mcp.slack.com/mcp"),
		ToolNamespace:  "slack",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "figma",
		Name:           "Figma",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "mcp-remote", "https://mcp.figma.com/mcp"]`),
		ToolNamespace:  "figma",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},

	// ── Stdio servers — no auth required ──
	{
		ID:             "filesystem",
		Name:           "Filesystem",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]`),
		ToolNamespace:  "fs",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "memory",
		Name:           "Memory",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-memory"]`),
		ToolNamespace:  "memory",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "sequential-thinking",
		Name:           "Sequential Thinking",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-sequential-thinking"]`),
		ToolNamespace:  "thinking",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "fetch",
		Name:           "Fetch",
		Transport:      "stdio",
		Command:        "uvx",
		Args:           json.RawMessage(`["mcp-server-fetch"]`),
		ToolNamespace:  "fetch",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "git",
		Name:           "Git",
		Transport:      "stdio",
		Command:        "uvx",
		Args:           json.RawMessage(`["mcp-server-git"]`),
		ToolNamespace:  "git",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "playwright",
		Name:           "Playwright",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@playwright/mcp@latest", "--headless", "--isolated"]`),
		ToolNamespace:  "playwright",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "docker",
		Name:           "Docker",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@docker/mcp-server"]`),
		ToolNamespace:  "docker",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "puppeteer",
		Name:           "Puppeteer",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-puppeteer"]`),
		ToolNamespace:  "puppeteer",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "context7",
		Name:           "Context7",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@upstash/context7-mcp@latest"]`),
		ToolNamespace:  "context7",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},

	// ── Stdio servers — require API keys / config ──
	{
		ID:             "brave-search",
		Name:           "Brave Search",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-brave-search"]`),
		ToolNamespace:  "brave",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "grafana",
		Name:           "Grafana",
		Transport:      "stdio",
		Command:        "uvx",
		Args:           json.RawMessage(`["mcp-grafana"]`),
		ToolNamespace:  "grafana",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	// ── Paddle (Billing) — official @paddle/paddle-mcp, stdio. Fixed env
	// (PADDLE_ENVIRONMENT, PADDLE_MCP_TOOLS) is supplied via the /usr/bin/env
	// wrapper so the auth scope only needs to carry PADDLE_API_KEY. Four
	// flavours exist so an agent's reachable toolset is bounded by the
	// chosen server, not by a UI toggle that could be flipped under it.
	{
		ID:             paddleServerSandboxReadID,
		Name:           "Paddle Sandbox (read-only)",
		Transport:      "stdio",
		Command:        "/usr/bin/env",
		Args:           json.RawMessage(`["PADDLE_ENVIRONMENT=sandbox","PADDLE_MCP_TOOLS=read-only","npx","-y","@paddle/paddle-mcp"]`),
		ToolNamespace:  "paddle_sandbox_ro",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             paddleServerSandboxWriteID,
		Name:           "Paddle Sandbox (read+write)",
		Transport:      "stdio",
		Command:        "/usr/bin/env",
		Args:           json.RawMessage(`["PADDLE_ENVIRONMENT=sandbox","PADDLE_MCP_TOOLS=all","npx","-y","@paddle/paddle-mcp"]`),
		ToolNamespace:  "paddle_sandbox",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             paddleServerProdReadID,
		Name:           "Paddle Production (read-only)",
		Transport:      "stdio",
		Command:        "/usr/bin/env",
		Args:           json.RawMessage(`["PADDLE_ENVIRONMENT=production","PADDLE_MCP_TOOLS=read-only","npx","-y","@paddle/paddle-mcp"]`),
		ToolNamespace:  "paddle_prod_ro",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             paddleServerProdWriteID,
		Name:           "Paddle Production (read+write, destructive)",
		Transport:      "stdio",
		Command:        "/usr/bin/env",
		Args:           json.RawMessage(`["PADDLE_ENVIRONMENT=production","PADDLE_MCP_TOOLS=all","npx","-y","@paddle/paddle-mcp"]`),
		ToolNamespace:  "paddle_prod",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:            aikidoServerID,
		Name:          "Aikido",
		Transport:     "internal",
		ToolNamespace: "aikido",
		Discovery:     "static",
		Disabled:      true,
		Source:        "default",
	},
	{
		ID:            freeagentServerID,
		Name:          "FreeAgent",
		Transport:     "internal",
		ToolNamespace: "freeagent",
		Discovery:     "static",
		Disabled:      true,
		Source:        "default",
	},
	{
		ID:            hammerspoonServerID,
		Name:          "Hammerspoon (macOS automation)",
		Transport:     "internal",
		ToolNamespace: "hammerspoon",
		Discovery:     "static",
		Disabled:      true,
		Source:        "default",
	},
	{
		ID:             "portainer",
		Name:           "Portainer",
		Transport:      "stdio",
		Command:        "portainer-mcp",
		Args:           json.RawMessage(`["-server", "localhost:9443", "-token", "YOUR_TOKEN"]`),
		ToolNamespace:  "portainer",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "exa",
		Name:           "Exa",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "exa-mcp-server"]`),
		ToolNamespace:  "exa",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "tavily",
		Name:           "Tavily",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "tavily-mcp"]`),
		ToolNamespace:  "tavily",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "gmaps",
		Name:           "Google Maps",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-google-maps"]`),
		ToolNamespace:  "gmaps",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	// ── Database servers ──
	{
		ID:             "postgres",
		Name:           "PostgreSQL",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-postgres", "postgresql://localhost:5432/mydb"]`),
		ToolNamespace:  "postgres",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "sqlite",
		Name:           "SQLite",
		Transport:      "stdio",
		Command:        "uvx",
		Args:           json.RawMessage(`["mcp-server-sqlite", "--db-path", "./data/mydb.db"]`),
		ToolNamespace:  "sqlite",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "redis",
		Name:           "Redis",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@modelcontextprotocol/server-redis", "redis://localhost:6379"]`),
		ToolNamespace:  "redis",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},
	{
		ID:             "turso",
		Name:           "Turso",
		Transport:      "stdio",
		Command:        "npx",
		Args:           json.RawMessage(`["-y", "@turso/mcp-server"]`),
		ToolNamespace:  "turso",
		Discovery:      "dynamic",
		IdleTimeoutSec: 300,
		MaxInstances:   1,
		RestartPolicy:  "on-failure",
		Disabled:       true,
		Source:         "default",
	},

	// ── Internal ──
	{
		// Self-CRUD over MCP. Backed by control.NewInternalBackend at
		// runtime; visibility gated by AdminCWDGate so these tools only
		// appear when the agent's CWD is at or under the data directory.
		ID:            "mcplexer",
		Name:          "MCPlexer Control",
		Transport:     "internal",
		ToolNamespace: "mcplexer",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "mcpx-builtin",
		Name:          "MCPlexer Built-in Tools",
		Transport:     "internal",
		ToolNamespace: "mcpx",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "mesh-builtin",
		Name:          "Agent Mesh",
		Transport:     "internal",
		ToolNamespace: "mesh",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "telegram",
		Name:          "Telegram",
		Transport:     "internal",
		ToolNamespace: "telegram",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "lmstudio",
		Name:          "LM Studio (local models)",
		Transport:     "internal",
		ToolNamespace: "lmstudio",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "secret-builtin",
		Name:          "Ephemeral Secret Prompts",
		Transport:     "internal",
		ToolNamespace: "secret",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "email-builtin",
		Name:          "Agent Email (SES, send-only)",
		Transport:     "internal",
		ToolNamespace: "email",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "memory-builtin",
		Name:          "Universal Memory (cross-harness facts + notes)",
		Transport:     "internal",
		ToolNamespace: "memory",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "task-builtin",
		Name:          "Universal Tasks (per-workspace operational primitive)",
		Transport:     "internal",
		ToolNamespace: "task",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "skill-builtin",
		Name:          "Skill Telemetry (W2: skill__run_start / __phase / __run_complete)",
		Transport:     "internal",
		ToolNamespace: "skill",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "brain-builtin",
		Name:          "Brain (agent-facing knowledge base: tree/list/get/search/write)",
		Transport:     "internal",
		ToolNamespace: "brain",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "data-builtin",
		Name:          "Data Workbench (code-mode scratch datasets: ingest/query/search)",
		Transport:     "internal",
		ToolNamespace: "data",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "kv-builtin",
		Name:          "Code-mode KV (cross-call scratch key/value)",
		Transport:     "internal",
		ToolNamespace: "kv",
		Discovery:     "static",
		Source:        "default",
	},
	{
		ID:            "index-builtin",
		Name:          "Code Index (local codebase indexer: build/symbols/deps/tests/context)",
		Transport:     "internal",
		ToolNamespace: "index",
		Discovery:     "static",
		Source:        "default",
	},
}
