package secrets

import (
	"bytes"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"filippo.io/age"
)

// AgeEncryptor encrypts and decrypts data using the age library.
type AgeEncryptor struct {
	identity  age.Identity
	recipient age.Recipient
}

// NewAgeEncryptor creates an AgeEncryptor from a key file path.
// The file should contain an age identity (private key).
func NewAgeEncryptor(keyPath string) (*AgeEncryptor, error) {
	data, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, fmt.Errorf("read age key file: %w", err)
	}
	return NewAgeEncryptorFromKey(string(data))
}

// NewAgeEncryptorFromKey creates an AgeEncryptor from a raw key string.
func NewAgeEncryptorFromKey(key string) (*AgeEncryptor, error) {
	identities, err := age.ParseIdentities(strings.NewReader(key))
	if err != nil {
		return nil, fmt.Errorf("parse age identity: %w", err)
	}
	if len(identities) == 0 {
		return nil, fmt.Errorf("no age identities found in key")
	}

	identity := identities[0]
	recipient, ok := identity.(*age.X25519Identity)
	if !ok {
		return nil, fmt.Errorf("unsupported age identity type")
	}

	return &AgeEncryptor{
		identity:  identity,
		recipient: recipient.Recipient(),
	}, nil
}

// NewEphemeralEncryptor creates an AgeEncryptor with an in-memory generated key.
// Tokens encrypted with this key are lost on restart. Useful for dev/testing.
func NewEphemeralEncryptor() (*AgeEncryptor, error) {
	id, err := age.GenerateX25519Identity()
	if err != nil {
		return nil, fmt.Errorf("generate ephemeral age key: %w", err)
	}
	return &AgeEncryptor{
		identity:  id,
		recipient: id.Recipient(),
	}, nil
}

// EnsureKeyFile loads an existing age key file, or generates a new one and
// writes it to keyPath. This gives persistent encryption across restarts
// without requiring manual key management.
//
// A missing key file alongside existing encrypted state means the key was
// deleted or the data dir was partially restored — generating a fresh key
// silently would orphan every secret encrypted under the old one, and the
// failure would only surface later as inexplicable decrypt errors. We still
// generate (the gateway must come up), but loudly.
func EnsureKeyFile(keyPath string) (*AgeEncryptor, error) {
	if data, err := os.ReadFile(keyPath); err == nil {
		return NewAgeEncryptorFromKey(string(data))
	}

	if dir := filepath.Dir(keyPath); hasEncryptedState(dir) {
		slog.Warn("age key file is missing but this data dir has prior state — "+
			"generating a NEW key; secrets encrypted under the old key are "+
			"unrecoverable without it. Restore the key file from backup to "+
			"recover them.",
			"key_path", keyPath, "data_dir", dir)
	}

	id, err := age.GenerateX25519Identity()
	if err != nil {
		return nil, fmt.Errorf("generate age key: %w", err)
	}

	content := fmt.Sprintf("# auto-generated by mcplexer\n# public key: %s\n%s\n",
		id.Recipient(), id)
	if err := os.WriteFile(keyPath, []byte(content), 0600); err != nil {
		return nil, fmt.Errorf("write age key file: %w", err)
	}

	return &AgeEncryptor{
		identity:  id,
		recipient: id.Recipient(),
	}, nil
}

// hasEncryptedState reports whether the data dir around the key path looks
// like an ESTABLISHED install rather than a fresh one: a non-empty secrets/
// or backups/ subdirectory. The DB file can't be the signal — it is created
// moments before the key on first boot. Heuristic by design; it only gates
// a warning, never the key generation itself.
func hasEncryptedState(dir string) bool {
	for _, sub := range []string{"secrets", "backups"} {
		if entries, err := os.ReadDir(filepath.Join(dir, sub)); err == nil && len(entries) > 0 {
			return true
		}
	}
	return false
}

// Encrypt encrypts plaintext using the age recipient.
func (e *AgeEncryptor) Encrypt(plaintext []byte) ([]byte, error) {
	var buf bytes.Buffer
	w, err := age.Encrypt(&buf, e.recipient)
	if err != nil {
		return nil, fmt.Errorf("create age writer: %w", err)
	}
	if _, err := w.Write(plaintext); err != nil {
		return nil, fmt.Errorf("write plaintext: %w", err)
	}
	if err := w.Close(); err != nil {
		return nil, fmt.Errorf("close age writer: %w", err)
	}
	return buf.Bytes(), nil
}

// Decrypt decrypts ciphertext using the age identity.
func (e *AgeEncryptor) Decrypt(ciphertext []byte) ([]byte, error) {
	r, err := age.Decrypt(bytes.NewReader(ciphertext), e.identity)
	if err != nil {
		return nil, fmt.Errorf("create age reader: %w", err)
	}
	plaintext, err := io.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("read decrypted data: %w", err)
	}
	return plaintext, nil
}
